version: '2'

services:
   apache_1:
      build: ./apache
      ports:
        - 8001:80
      volumes:
        - ./www/:/var/www/html/
        - ./logs/apache/:/usr/local/apache2/logs
        - ./apache/docker.apache.conf:/usr/local/apache2/conf.d/docker.apache.conf
      restart: always
      depends_on: 
        - php
   php:
      build: ./php
      volumes: 
        - ./www/:/var/www/html/
   mysql:
      image: mysql
      volumes:
        - ./mysql/data/:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=docker    
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - 3307:3306
   adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      links:
        - mysql:db

